spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deposits
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update